metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
block_size = 1048576
replication_factor = 1

rpc_bind_addr = "0.0.0.0:3902"
rpc_public_addr = "garage:3902"
rpc_secret = "${GARAGE_RPC_SECRET}"

[s3_api]
api_bind_addr = "0.0.0.0:3900"
s3_region = "${GARAGE_S3_REGION}"
root_domain = "${GARAGE_S3_ROOT_DOMAIN}"

[admin]
api_bind_addr = "0.0.0.0:3901"
admin_token = "${GARAGE_ADMIN_TOKEN}"
